### ISSUE TITLE
compile issue...

### ISSUE THREAD

**Issue by luckybulldozer** [vgvishesh/Splat-Generator#1]
Awesome way to render point clouds in blender!   (I just can't compile it!)
What am I doing wrong here...?

$ g++-4.8 main.cpp plyloader_C_Binary.cpp -o PLYLOader
main.cpp:16:1: error: 'main' must return 'int'
void main()
^~~~
int
1 error generated.
plyloader_C_Binary.cpp:140:19: error: call to 'sqrt' is ambiguous
        float magNormal= sqrt(nor.x_nor.x + nor.y_nor.y + nor.z \* nor.z);
                         ^~~~
/Library/Developer/CommandLineTools/usr/bin/../lib/c++/v1/cmath:1008:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       sqrt(float __x) _NOEXCEPT       {return sqrtf(__x);}
                                             ^
/usr/local/include/glm/detail/func_exponential.inl:198:27: note: candidate function
        GLM_FUNC_QUALIFIER float sqrt(float x)
                                 ^
/usr/include/math.h:447:15: note: candidate function
extern double sqrt(double);
              ^
/usr/local/include/glm/detail/func_exponential.inl:208:28: note: candidate function
        GLM_FUNC_QUALIFIER double sqrt(double x)
                                  ^
/Library/Developer/CommandLineTools/usr/bin/../lib/c++/v1/cmath:1009:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long double sqrt(long double __x) _NOEXCEPT {return sqrtl(__x);}
                                             ^
plyloader_C_Binary.cpp:161:42: warning: format specifies type 'int' but the argument has type 'unsigned long' [-Wformat]
        fprintf(outputPly,"element vertex %d\n",4*vertexCount);
                                          ~~    ^~~~~~~~~~~~~
                                          %lu
plyloader_C_Binary.cpp:172:40: warning: format specifies type 'int' but the argument has type 'unsigned long' [-Wformat]
        fprintf(outputPly,"element face %d\n",vertexCount);
                                        ~~    ^~~~~~~~~~~
                                        %lu
2 warnings and 1 error generated.
nz7-10516:Splat-Generator dmonaghan$

**Comment by vgvishesh** [comment]
Hi,

The issue that you are getting is simple to resolve, just change the return type of main() function to instead of void. In my case it worked as I compiled it on visual studios. :)

**Comment by luckybulldozer** [comment]
Hi Vishesh,

Really love the idea of rendering out pointcoulds in blender, so a big thanks for your reply.., Alas, I’ve tried changing main.cpp to ;

```
#include<iostream>
#include "plyloader.h"

using namespace std;

int main()
{
    PLYModel MODEL("test_m_bin.ply");
    //MODEL.PLYSplatedModel("test_computed_ascii.ply",0.05);
    cout<<"\nModel Generated....\n";
    system("pause");
    return 0;
}
```

& my compile options are probably completely incorrect… e.g.,

```
$ g++-4.8 -o main main.cpp plyloader_C_Binary.cpp plyloader.h
```

which does compile, but gives me a 15meg binary!  …
any clues?  I’d really like to see this working as I do some pretty mad point cloud stuff like this…

http://vimeo.com/luckybulldozer/sifted

Thanks,

Dan Monaghan

below is the log from my compile...

```
plyloader_C_Binary.cpp: In function 'void makeSplat(glm::vec3&, glm::vec3, glm::vec3)':
plyloader_C_Binary.cpp:140:65: error: call of overloaded 'sqrt(float)' is ambiguous
  float magNormal= sqrt(nor.x*nor.x + nor.y*nor.y + nor.z * nor.z);
                                                                 ^
plyloader_C_Binary.cpp:140:65: note: candidates are:
In file included from plyloader_C_Binary.cpp:15:0:
/usr/local/Cellar/gcc48/4.8.3/lib/gcc/x86_64-apple-darwin13.0.0/4.8.3/include-fixed/math.h:462:15: note: double sqrt(double)
 extern double sqrt(double);
               ^
In file included from /usr/local/include/glm/detail/func_exponential.hpp:130:0,
                 from /usr/local/include/glm/exponential.hpp:32,
                 from /usr/local/include/glm/glm.hpp:109,
                 from plyloader.h:15,
                 from plyloader_C_Binary.cpp:18:
/usr/local/include/glm/detail/func_exponential.inl:208:28: note: double glm::sqrt(double)
  GLM_FUNC_QUALIFIER double sqrt(double x)
                            ^
/usr/local/include/glm/detail/func_exponential.inl:198:27: note: float glm::sqrt(float)
  GLM_FUNC_QUALIFIER float sqrt(float x)
                           ^
In file included from /usr/local/include/glm/detail/_fixes.hpp:29:0,
                 from /usr/local/include/glm/glm.hpp:78,
                 from plyloader.h:15,
                 from plyloader_C_Binary.cpp:18:
/usr/local/Cellar/gcc48/4.8.3/lib/gcc/x86_64-apple-darwin13.0.0/4.8.3/include/c++/cmath:486:3: note: long double std::sqrt(long double)
   sqrt(long double __x)
   ^
/usr/local/Cellar/gcc48/4.8.3/lib/gcc/x86_64-apple-darwin13.0.0/4.8.3/include/c++/cmath:482:3: note: float std::sqrt(float)
   sqrt(float __x)
   ^
```

**Comment by vgvishesh** [comment]
Hi Dan,

I compiled the project again using g++ compiler in CodeBlocks IDE. It ran fine on my system, without any errors.
Things that I think might be going wrong with you can be-
1. The compile command that you are giving. you can check this link for help, http://stackoverflow.com/questions/3202136/using-g-to-compile-multiple-cpp-and-h-files

However, I did not use the command line to link the .cpp files, I used the codeblocks IDE instead. You can try going for an IDE.
1. plyloader_C_Binary.cpp:140:19: error: call to 'sqrt' is ambiguous
   float magNormal= sqrt(nor.x_nor.x + nor.y_nor.y + nor.z \* nor.z);
   This error might be occurring because of new version (c++11 version) of math.h library on your system.
   To correct this, replace the line by:
   double magNormal= sqrt((double)nor.x_nor.x + nor.y_nor.y + nor.z \* nor.z);

Hope it works :)
Looked at your work, its very awesome....  \m/
I have also made a software which takes in meshes and point clouds, renders them and allows you to create walk through in them, which will move the camera in the scene, all in real time. 
http://visheshvision.com/2014/07/11/point-cloud-rendering-engine/

**Comment by luckybulldozer** [comment]
Hi Vishesh,
Thanks for all that, I'm now trying to compile on Windows with Codeblocks and GCC,  so I had to change main.cpp to return an it, and also had to add #include<cstdlib>, which I thought may be strange since it's definitely in plyloader.  Now on trying to compile I get an error;

```
undefined reference to`PLYModel::PLYModel(char const*)'
```

Glad you liked the film, it's really something for people like us!  Also checked out your Point Cloud engine, looks great & very fast!
Cheers,
Dan

**Comment by vgvishesh** [comment]
I think that is because you are trying to compile the main.cpp only. That is why the compiler is complaining " undefined reference " , which simply means, that it is not able to locate the function's declaration and definition.

To resolve this you need to make a project in CobeBlocks instead, if you are trying to compile a single file.  If you have made a project, then for things to work smoothly, you need to add all the three source code files in the source directory. 
Just search online how to build a project in CodeBlocks, I am sure there will numerous links telling so. 

Since code runs fine on my machine on both visual studios and CodeBlocks, so there is no error in the code. The only thing that is stopping the code to run on your machine could be the improper linking of the files.

**Comment by saimon86** [comment]
Hi guys!
Vishesh your software is very very interesting but there is a problem: I'm not very good in compiling : /

I saw the ".exe" file so, correct if I'm wrong, probably I can bypass the commpiling moment using directly the ".exe" file, is it correct?

If my conclusion is correct: what I have to do now? 

You wrote ".exe usage from windows command line", so could you make me an example of standard commands that I have to type for use your software?

Sorry, I know that probably my questions are "stupid" but I'm very intresting on your software because I would like to render a point cloud in blender and then create a short movie with a camera..

Thank you for your attention

Simone

**Comment by vgvishesh** [comment]
Yeah, you can use the .exe directly on windows machine. 
In the readme file of the project i have added the sample command to run the .exe
